# Generated by Django 4.1.3 on 2022-11-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('keywords', models.CharField(max_length=255, verbose_name='keywords')),
                ('annotation', models.CharField(max_length=255, verbose_name='annotation')),
                ('rubNum', models.IntegerField(verbose_name='rubNum')),
            ],
        ),
    ]
