# Generated by Django 4.1.3 on 2022-11-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_rub'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hash',
            field=models.ManyToManyField(null=True, to='main.hashtag'),
        ),
    ]
