# Generated by Django 4.1.3 on 2022-11-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rubNum',
        ),
        migrations.AlterField(
            model_name='article',
            name='annotation',
            field=models.CharField(max_length=1100, verbose_name='annotation'),
        ),
    ]
