# Generated by Django 4.1.3 on 2022-11-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
