# Generated by Django 4.1.3 on 2022-11-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('keywords', models.CharField(max_length=255, verbose_name='keywords')),
                ('image', models.CharField(max_length=255, verbose_name='image')),
                ('annotation', models.CharField(max_length=1100, verbose_name='annotation')),
                ('hash', models.ManyToManyField(null=True, to='main.hashtag')),
                ('rub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.rubric')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
