# Generated by Django 4.1.3 on 2022-11-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_article_image_article_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.ManyToManyField(to='main.hashtag'),
        ),
    ]
